import { Inter, Figtree } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import Footer from "@/components/footer/footer";

const figtree = Figtree({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={figtree.className}
        style={{ margin: "auto", maxWidth: "1728px" }}
      >
        <AntdRegistry>
          <ConfigProvider
            theme={{
              token: {
                fontFamily: figtree.style.fontFamily, // Apply Figtree font to all Ant Design components
              },
              components: {
                Button: {
                  fontSize: "18px",
                  fontWeight: "bold",
                  padding: "16px 20px 16px 20px",
                  colorText: "#233240",

                  colorTextSecondary: "#2C3F50",
                },
                Typography: {
                  fontSizeHeading1: "32px",
                  fontSize: "24px",
                },
              },
            }}
          >
            {children}
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
